### PR TITLE
Auto routing 

### PR DESCRIPTION
**Pull request by Weepfrog**
put the paths into main so i can branch off of it

### CODE REVIEW

**Comment by prensing** [comment]
Needs a merge from main.

**Review by prensing — CHANGES_REQUESTED** [review]
Seems fine, but pathplanner/navgrid.json still is different from main. Not sure what that file is for.

**Review by coachFitz0807 — COMMENTED** [review]
YOU should merge out from main again and resubmit the PR. PR 14 got merged after the last time you merged out.

**Comment by Weepfrog** [comment]
I made a new branch off main and put the paths into it

**Pull request closed without merging**
